### ISSUE TITLE
Missing configuration options

### ISSUE THREAD

**Issue by chroche** [sansible/users_and_groups#14]
Two configurations options are lacking at that time:
 1. Ability to set the user home directory to something else than the default '/home/username'
 2. Ability to set the SSH authorized_keys file to something else than the default '/home/username/.ssh/authorized_keys'

These two are required when creating a chroot-enabled SFTP server, cf for instance [here](https://wiki.archlinux.org/index.php/SFTP_chroot).

**Comment by lobsterdore** [comment]
Closed by #15
