### ISSUE TITLE
Home folder should always have `user:user_group` owner

### ISSUE THREAD

**Issue by wojtek-oledzki** [sansible/users_and_groups#3]
As a user
I want my home folder to be owned by my user and group
So that I can read/write to it
#### Notes

if a home folder already exists, this role does not ensure correct folder ownership.

**Comment by dm** [comment]
@wojtek-oledzki Does the commit 84fe9d7cb631e9b55e6acafa66252d4b66610339 not update permissions correctly already?

Although: `when: not (item.createhome is defined and not item.createhome)`

**Comment by wojtek-oledzki** [comment]
done in #4
