### ISSUE TITLE
Creation of SSH directory fails since latest commit

### ISSUE THREAD

**Issue by hwwilliams** [sansible/users_and_groups#34]
I setup another server a week or two ago and the same variables worked fine then.

It sets up the groups, user, and sudoers file fine but fails once it tries to create the .ssh directory.

Ansible version information:
![image](https://user-images.githubusercontent.com/20447447/52190444-2b70a800-280d-11e9-87b1-7ea04a5123f4.png)

Error:
![image](https://user-images.githubusercontent.com/20447447/52190368-c7e67a80-280c-11e9-8f9d-6e5dec3ac900.png)

Variables used:
![image](https://user-images.githubusercontent.com/20447447/52190467-578c2900-280d-11e9-8649-085d2732f375.png)

**Comment by lobsterdore** [comment]
@hwwilliams taking a look at this now

**Comment by lobsterdore** [comment]
@hwwilliams OK I've fixed this, just waiting for the tests to pass on the PR

**Comment by lobsterdore** [comment]
@hwwilliams all fixed in version v2.0.4
